# Minimal makefile for Sphinx documentation

SPHINXBUILD	= sphinx-build
SPHINXOPTS	=
SOURCEDIR	= $(PWD)
OUTPUTDIR	= $(PWD)/../public/docs

.PHONY: html
%: html
	@$(SPHINXBUILD) $(SPHINXOPTS) "$(SOURCEDIR)" "$(OUTPUTDIR)"
