---

# This workflow will install Python dependencies, run tests and lint with a
# single version of Python

# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: python-helloworld
permissions:
  contents: read
  pull-requests: write

on:   # yamllint disable-line rule:truthy
  push:
    branches: ["master", "feature*"]
  pull_request:
    branches: ["master", "feature*"]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: "setup python 3.13"
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --requirement requirements.txt
          python --version
          pytest --version
          pip --version
          pip list --local

      - name: check
        run: |
          ruff format --check
          sort-requirements --check requirements.txt

      - name: tests
        run: >
          pytest --verbose --color=yes
          --html=cover/unittests.html --self-contained-html
          --cov=helloworld --cov-report=html:cover

      - name: run
        run: |
          python -m helloworld -h
          python -m helloworld --version
          python -m helloworld --log DEBUG
